# Generated by Django 6.0.5 on 2026-07-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_alter_property_options_property_created_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='data_type',
            field=models.CharField(choices=[('number', 'Число'), ('string', 'Строка'), ('boolean', 'Да/Нет'), ('date', 'Дата'), ('material_link', 'Материал')], default='number', max_length=20),
        ),
    ]
