# Generated by Django 6.0.5 on 2026-07-15 08:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_property_material_link_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='data_type',
            field=models.CharField(choices=[('number', 'Число'), ('string', 'Строка'), ('boolean', 'Да/Нет'), ('date', 'Дата'), ('material_link', 'Материал'), ('choice', 'Выбор из списка')], default='number', max_length=20),
        ),
        migrations.CreateModel(
            name='PropertyChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200, verbose_name='Название')),
                ('value', models.CharField(max_length=100, verbose_name='Код')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='references.property', verbose_name='Свойство')),
            ],
            options={
                'verbose_name': 'Вариант свойства',
                'verbose_name_plural': 'Варианты свойства',
                'ordering': ['sort_order', 'label', 'value'],
                'unique_together': {('property', 'value')},
            },
        ),
    ]
