# Generated by Django 6.0.5 on 2026-07-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_property_choice_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='decimal_places',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
