# Generated by Cursor on 2026-05-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0003_dynamic_tables'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='struct_props_id',
            field=models.UUIDField(
                blank=True,
                null=True,
                verbose_name='ID параметров структуры',
            ),
        ),
        migrations.AddField(
            model_name='material',
            name='struct_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='materials',
                to='structures.structuretype',
                verbose_name='Тип структуры',
            ),
        ),
    ]
