# Generated by Django 6.0.5 on 2026-05-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_material_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['code'], 'verbose_name': 'материал', 'verbose_name_plural': 'материалы'},
        ),
        migrations.AlterField(
            model_name='material',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='material',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
    ]
