# Generated by Django 6.0.6 on 2026-06-30 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_tag'),
        ('materials', '0005_alter_material_options_alter_material_code_and_more'),
        ('structures', '0011_structuretype_home_workspace_and_more'),
        ('workspaces', '0002_alter_workspace_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_materials', to=settings.AUTH_USER_MODEL, verbose_name='Создал (пользователь)'),
        ),
        migrations.AddField(
            model_name='material',
            name='home_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_materials', to='workspaces.workspace', verbose_name='Домашнее пространство'),
        ),
        migrations.AddField(
            model_name='material',
            name='published_workspaces',
            field=models.ManyToManyField(blank=True, related_name='published_materials', to='workspaces.workspace', verbose_name='Опубликовано в пространствах'),
        ),
        migrations.AddField(
            model_name='material',
            name='visibility_mode',
            field=models.CharField(choices=[('private', 'Только домашнее пространство'), ('selected_workspaces', 'Выбранные пространства'), ('all_workspaces', 'Все пространства')], default='all_workspaces', max_length=32, verbose_name='Режим видимости'),
        ),
        migrations.AddField(
            model_name='materialattachment',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_attachments', to='workspaces.workspace', verbose_name='Пространство'),
        ),
        migrations.AlterField(
            model_name='material',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Код'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('home_workspace', 'code'), name='unique_material_code_per_workspace'),
        ),
    ]
