# Generated by Django 6.0.6 on 2026-07-01 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_material_created_by_user_material_home_workspace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialattachment',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Загрузил'),
        ),
        migrations.AddField(
            model_name='materialattachment',
            name='uploaded_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_material_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил (пользователь)'),
        ),
    ]
