# Generated by Django 6.0.5 on 2026-07-16 08:19

from decimal import Decimal, InvalidOperation

from django.db import migrations, models


def backfill_scalar_bounds(apps, schema_editor):
    MaterialProperty = apps.get_model('materials', 'MaterialProperty')
    for row in MaterialProperty.objects.exclude(value='').iterator():
        try:
            decimal_value = Decimal(str(row.value).replace(',', '.'))
        except InvalidOperation:
            continue
        row.value_min = decimal_value
        row.value_max = decimal_value
        row.save(update_fields=['value_min', 'value_max'])


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_materialattachment_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialproperty',
            name='value_kind',
            field=models.CharField(choices=[('scalar', 'Точное'), ('range', 'Диапазон')], default='scalar', max_length=10),
        ),
        migrations.AddField(
            model_name='materialproperty',
            name='value_max',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='materialproperty',
            name='value_min',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True),
        ),
        migrations.RunPython(backfill_scalar_bounds, migrations.RunPython.noop),
    ]
