# Generated by Django 6.0.6 on 2026-07-20 08:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_property_number_value_slots'),
        ('workspaces', '0006_workspace_material_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialImportProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Название профиля')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Конфигурация маппинга')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_import_profiles', to='workspaces.workspace', verbose_name='Пространство')),
            ],
            options={
                'verbose_name': 'профиль импорта материалов',
                'verbose_name_plural': 'профили импорта материалов',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'name'), name='unique_material_import_profile_per_workspace')],
            },
        ),
    ]
