# Generated by Django 6.0.6 on 2026-07-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0012_material_import_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
    ]
