# Generated by Django 6.0.6 on 2026-07-22 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_material_import_source_filename'),
        ('references', '0006_material_metadata_dictionaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='references.availability', verbose_name='Доступность'),
        ),
        migrations.AddField(
            model_name='material',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='references.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='material',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='references.technology', verbose_name='Технология'),
        ),
    ]
