# Generated by Django 6.0.6 on 2026-07-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0015_material_metadata_dictionaries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialimportprofile',
            options={'ordering': ['name'], 'verbose_name': 'шаблон импорта материалов', 'verbose_name_plural': 'шаблоны импорта материалов'},
        ),
        migrations.AlterField(
            model_name='materialimportprofile',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Конфигурация шаблона'),
        ),
        migrations.AlterField(
            model_name='materialimportprofile',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название шаблона'),
        ),
    ]
