# Generated by Django 6.0.6 on 2026-08-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0016_rename_import_profile_to_template_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialattachment',
            name='preview_pdf',
            field=models.FileField(blank=True, help_text='PDF для просмотра: копия PDF или результат конвертации Word.', upload_to='material_attachments/previews/%Y/%m/%d/', verbose_name='Превью (PDF)'),
        ),
        migrations.AddField(
            model_name='materialattachment',
            name='preview_status',
            field=models.CharField(choices=[('none', 'Нет'), ('skipped', 'Не требуется'), ('pending', 'Обработка'), ('ready', 'Готово'), ('failed', 'Ошибка')], default='none', max_length=20, verbose_name='Статус превью'),
        ),
    ]
