# Generated by Django 6.0.6 on 2026-07-29 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tag_metadata'),
        ('workspaces', '0006_workspace_material_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('material', 'Материал'), ('sample', 'Образец'), ('scan', 'Скан')], max_length=20, verbose_name='Тип объекта')),
                ('entity_id', models.UUIDField(verbose_name='ID объекта')),
                ('parent_id', models.UUIDField(blank=True, help_text='Для сканов — UUID образца.', null=True, verbose_name='Родительский ID')),
                ('label', models.CharField(blank=True, max_length=300, verbose_name='Подпись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookmarks', to='workspaces.workspace', verbose_name='Пространство')),
            ],
            options={
                'verbose_name': 'закладка',
                'verbose_name_plural': 'закладки',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'workspace', 'entity_type', 'entity_id'), name='unique_user_bookmark_per_entity')],
            },
        ),
    ]
