# Generated by Django 6.0.6 on 2026-07-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookmark',
            name='context_slug',
            field=models.CharField(blank=True, help_text='Для записей структуры — code типа структуры.', max_length=100, verbose_name='Контекст (slug)'),
        ),
        migrations.AlterField(
            model_name='userbookmark',
            name='entity_type',
            field=models.CharField(choices=[('material', 'Материал'), ('sample', 'Образец'), ('scan', 'Скан'), ('structure_record', 'Запись структуры')], max_length=20, verbose_name='Тип объекта'),
        ),
    ]
