# Generated by Django 6.0.6 on 2026-07-30 11:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userbookmark_context_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookmark',
            name='entity_type',
            field=models.CharField(choices=[('material', 'Материал'), ('sample', 'Образец'), ('scan', 'Скан'), ('structure_record', 'Запись структуры'), ('structure_type', 'Тип структуры')], max_length=20, verbose_name='Тип объекта'),
        ),
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('trigger', models.CharField(choices=[('manual', 'Вручную'), ('scheduled', 'По расписанию')], max_length=10, verbose_name='Запуск')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='running', max_length=10, verbose_name='Статус')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Размер, байт')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backup_runs', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'запуск резервного копирования',
                'verbose_name_plural': 'запуски резервного копирования',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Резервное копирование включено')),
                ('schedule_hour', models.IntegerField(default=3, help_text='От 0 до 23.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Час запуска')),
                ('schedule_minute', models.IntegerField(default=0, help_text='От 0 до 59.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='Минута запуска')),
                ('retention_count', models.PositiveIntegerField(default=7, verbose_name='Количество хранимых копий')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_backup_settings', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'настройка резервного копирования',
                'verbose_name_plural': 'настройки резервного копирования',
            },
        ),
    ]
