# Generated by Django 6.0.6 on 2026-07-30 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userbookmark_entity_type_backuprun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupsettings',
            name='retention_count',
            field=models.PositiveIntegerField(default=7, help_text='Минимум 1.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество хранимых копий'),
        ),
    ]
