# Generated by Django 6.0.6 on 2026-07-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_backupsettings_retention_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuprun',
            name='trigger',
            field=models.CharField(choices=[('manual', 'Вручную'), ('scheduled', 'По расписанию'), ('restore', 'Восстановление')], max_length=10, verbose_name='Запуск'),
        ),
        migrations.AlterField(
            model_name='backupsettings',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Авто копирование'),
        ),
    ]
