# Generated by Django 6.0.6 on 2026-07-30 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_backuprun_restore_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupsettings',
            name='interval_days',
            field=models.PositiveIntegerField(default=1, help_text='1 — каждый день, 7 — раз в неделю, и т.д. (1–365).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Интервал, дней'),
        ),
    ]
