# Generated by Django 6.0.6 on 2026-08-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userbookmark_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookmark',
            name='icon_color',
            field=models.CharField(blank=True, help_text='HEX #RRGGBB для иконки закладки страницы; пусто — цвет по умолчанию.', max_length=7, verbose_name='Цвет иконки'),
        ),
    ]
