# Generated by Django 6.0.5 on 2026-05-20 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StructureInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('structure_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structures.structuretype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StructureField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('CharField', 'Строка'), ('TextField', 'Текст'), ('IntegerField', 'Целое число'), ('DecimalField', 'Десятичная дробь'), ('FloatField', 'Число с плавающей точкой'), ('BooleanField', 'Да/Нет'), ('DateField', 'Дата'), ('DateTimeField', 'Дата и время'), ('ForeignKey', 'Связь с другой моделью')], max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=500)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
                ('max_digits', models.IntegerField(blank=True, null=True)),
                ('decimal_places', models.IntegerField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('foreign_key_model', models.CharField(blank=True, max_length=200)),
                ('structure_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='structures.structuretype')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('structure_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StructureFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('value_integer', models.IntegerField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('value_fk_id', models.UUIDField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structures.structurefield')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='structures.structureinstance')),
            ],
            options={
                'unique_together': {('instance', 'field')},
            },
        ),
    ]
