# Generated by Django 6.0.5 on 2026-05-20 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandwichStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_thickness', models.DecimalField(decimal_places=2, max_digits=8)),
                ('core_material', models.CharField(max_length=200)),
                ('structure_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sandwich_data', to='structures.structureinstance')),
            ],
            options={
                'verbose_name': 'Сэндвич',
                'verbose_name_plural': 'Сэндвич',
                'db_table': 'structures_sandwich',
            },
        ),
    ]
