# Generated by Django 6.0.5 on 2026-05-20 14:52

from django.db import migrations, models


def populate_table_names(apps, schema_editor):
    StructureType = apps.get_model('structures', 'StructureType')
    for st in StructureType.objects.all():
        if not st.table_name:
            st.table_name = f'structures_{st.code}'.replace('-', '_')
            st.save(update_fields=['table_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0002_sandwichstructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='structureinstance',
            name='dynamic_row_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='structuretype',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structuretype',
            name='table_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='structurefield',
            name='decimal_places',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='structurefield',
            name='max_digits',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='structurefield',
            name='max_length',
            field=models.IntegerField(blank=True, default=255, null=True),
        ),
        migrations.RunPython(populate_table_names, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='SandwichStructure',
        ),
    ]
