# Generated by Django 6.0.5 on 2026-05-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0007_structuretype_allow_layers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structureinstance',
            name='structure_type',
        ),
        migrations.DeleteModel(
            name='StructureFieldValue',
        ),
        migrations.DeleteModel(
            name='StructureInstance',
        ),
    ]
