# Generated by Django 6.0.5 on 2026-06-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0008_remove_legacy_instance_and_field_value_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuretype',
            name='display_color',
            field=models.CharField(choices=[('tone-coral', 'Коралловый'), ('tone-amber', 'Янтарный'), ('tone-green', 'Зелёный'), ('tone-blue', 'Синий'), ('tone-violet', 'Фиолетовый'), ('tone-rose', 'Розовый'), ('tone-teal', 'Бирюзовый'), ('tone-slate', 'Серый')], default='tone-teal', help_text='Отображается в списке материалов и карточках с этим типом структуры.', max_length=20, verbose_name='Цвет в интерфейсе'),
        ),
    ]
