# Generated by Django 6.0.5 on 2026-06-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0009_structuretype_display_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structurefield',
            name='decimal_places',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
