# Generated by Django 6.0.6 on 2026-06-30 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0010_default_decimal_places_four'),
        ('workspaces', '0002_alter_workspace_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuretype',
            name='home_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_structure_types', to='workspaces.workspace', verbose_name='Домашнее пространство'),
        ),
        migrations.AddField(
            model_name='structuretype',
            name='published_workspaces',
            field=models.ManyToManyField(blank=True, related_name='published_structure_types', to='workspaces.workspace', verbose_name='Опубликовано в пространствах'),
        ),
        migrations.AddField(
            model_name='structuretype',
            name='visibility_mode',
            field=models.CharField(choices=[('private', 'Только домашнее пространство'), ('selected_workspaces', 'Выбранные пространства'), ('all_workspaces', 'Все пространства')], default='all_workspaces', max_length=32, verbose_name='Режим видимости'),
        ),
    ]
