# Generated by Django 6.0.5 on 2026-07-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0013_structurefield_choice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structurefield',
            name='decimal_places',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
