# Generated by Django 6.0.5 on 2026-05-29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
        ('samples', '0005_sample_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_values', to='references.property')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='samples.sample')),
            ],
            options={
                'unique_together': {('sample', 'property')},
            },
        ),
    ]
