# Generated by Django 6.0.5 on 2026-05-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_sampleproperty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['code']},
        ),
        migrations.AlterField(
            model_name='sampleattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Загружен'),
        ),
    ]
