# Generated by Django 6.0.6 on 2026-06-30 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_tag'),
        ('materials', '0006_material_created_by_user_material_home_workspace_and_more'),
        ('samples', '0007_alter_sample_options_and_more'),
        ('workspaces', '0002_alter_workspace_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_samples', to=settings.AUTH_USER_MODEL, verbose_name='Создал (пользователь)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='workspaces.workspace', verbose_name='Пространство'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='unique_sample_code_per_workspace'),
        ),
    ]
