# Generated by Django 6.0.6 on 2026-07-01 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_sample_created_by_user_sample_workspace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleattachment',
            name='uploaded_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_sample_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил (пользователь)'),
        ),
    ]
