# Generated by Django 6.0.6 on 2026-08-13 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0015_attachment_preview_image'),
        ('structures', '0015_structuretype_display_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='struct_props_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='ID параметров структуры'),
        ),
        migrations.AddField(
            model_name='sample',
            name='struct_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='structures.structuretype', verbose_name='Тип структуры'),
        ),
    ]
