# Generated by Django 6.0.5 on 2026-07-07 08:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_materialattachment_uploaded_by_and_more'),
        ('workspaces', '0005_operator_material_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceMaterialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_links', to='materials.material', verbose_name='Материал')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_links', to='workspaces.workspace', verbose_name='Пространство')),
            ],
            options={
                'verbose_name': 'ссылка на материал',
                'verbose_name_plural': 'ссылки на материалы',
                'constraints': [models.UniqueConstraint(fields=('workspace', 'material'), name='unique_workspace_material_link')],
            },
        ),
    ]
