# Generated by Django 6.0.5 on 2026-05-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_scanrecord_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanrecord',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'скан', 'verbose_name_plural': 'сканы'},
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='file',
            field=models.FileField(upload_to='scans/%Y/%m/%d/', verbose_name='Файл скана (HDF5)'),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Загружен'),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Загрузил'),
        ),
    ]
