# Generated by Django 6.0.6 on 2026-06-30 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_alter_scanrecord_options_and_more'),
        ('workspaces', '0002_alter_workspace_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecord',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scan_records', to='workspaces.workspace', verbose_name='Пространство'),
        ),
    ]
