# Generated by Django 6.0.6 on 2026-08-07 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0009_scanrecord_preview'),
        ('workspaces', '0006_workspace_material_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='scan_attachments/%Y/%m/%d/', verbose_name='Файл')),
                ('preview_pdf', models.FileField(blank=True, help_text='PDF для просмотра: копия PDF или результат конвертации Word.', upload_to='scan_attachments/previews/%Y/%m/%d/', verbose_name='Превью (PDF)')),
                ('preview_status', models.CharField(choices=[('none', 'Нет'), ('skipped', 'Не требуется'), ('pending', 'Обработка'), ('ready', 'Готово'), ('failed', 'Ошибка')], default='none', max_length=20, verbose_name='Статус превью')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('uploaded_by', models.CharField(blank=True, max_length=100, verbose_name='Загрузил')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='scans.scanrecord', verbose_name='Скан')),
                ('uploaded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_scan_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил (пользователь)')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scan_attachments', to='workspaces.workspace', verbose_name='Пространство')),
            ],
            options={
                'verbose_name': 'вложение скана',
                'verbose_name_plural': 'вложения сканов',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
