# Generated by Django 6.0.5 on 2026-05-25

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0002_material_structure_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layer_number', models.PositiveIntegerField(verbose_name='Номер слоя')),
                ('angle', models.FloatField()),
                ('thickness', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_composite_layers', to='materials.material')),
                ('parent_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composite_layers', to='materials.material')),
            ],
            options={
                'ordering': ['layer_number'],
                'unique_together': {('parent_material', 'layer_number')},
            },
        ),
    ]
